# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Escriba el nombre del proveedor', max_length=50)),
                ('tel', models.CharField(help_text='Escriba el numero del proveedor', max_length=12)),
                ('email', models.EmailField(help_text='Ingrese el email de contacto del proveedor', max_length=254)),
                ('startre', models.DateField(help_text='Seleccione la fecha de inicio de relación con el proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(help_text='Escriba el nombre del producto', max_length=40)),
                ('Clasificacition', models.CharField(help_text='Escriba la Clasificacicion', max_length=40)),
                ('Date', models.DateField(auto_now=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('F', 'Food'), ('A', 'Accesories'), ('D', 'Drugs'), ('T', 'Toys')], help_text='Seleccione la categoria', max_length=1)),
                ('Parner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Especies.partner')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(help_text='Ingrese la cantidad de productos existentes')),
                ('pubdate', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Especies.product')),
            ],
        ),
    ]
